site_name: Learn Data Engineering
site_url: https://karlchris.github.io/learn-data-engineering/

nav:
  - Overview: 'index.md'
  - Data Modeling:
    - 'data-modeling/README.md'
    - Dimensional Modeling: 'data-modeling/dimensional-modeling/README.md'
    - DDL vs. DML: 'data-modeling/ddl-vs-dml/README.md'
    - Query Life Cycle: 'data-modeling/query-lifecycle/README.md'

# Github spec
repo_url: https://github.com/karlchris/learn-data-engineering

theme:
  name: material

  favicon: assets/img/database-storage.png
  logo: assets/img/logo.svg

  font:
    text: Fira Sans
    code: Fira Code

  features:
    - navigation.instant
    - navigation.top
    - toc.integrate

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
