site_name: Learn Data Engineering
site_url: https://karlchris.github.io/learn-data-engineering/
theme:
  name: material

nav:
  - Data Modeling: 'docs/data-modeling/README.md'
  - Learning Python: 'docs/learning-python/README.md'
